In [2]:
from Module1 import *
a=4
carre(a)

16

In [3]:

r_carre(a)

2.0

In [4]:
doubler(a)


8

In [5]:
tripler(a)

12

In [6]:
import math
math.log(1)

0.0

In [7]:
import statistics
liste=[12,13,4,8,3,69]
statistics.mean(liste)

18.166666666666668

In [8]:
statistics.variance(liste)

636.5666666666667

In [9]:
import random 
print (random.randint(4,1000))

791


In [10]:
print(random.random())

0.3822975585419459


In [11]:
print(random.randrange(1000))

606


In [12]:
print(random.uniform(4,456))

107.97278228492851


In [13]:
random.seed(0)
liste=[12,13,4,8,3,69]
print(random.choice(liste))

8


In [14]:
noms=["Eddie","Sara","Moussa","Jean","Youssef"]
print(random.choices(noms, k=3))

['Jean', 'Moussa', 'Sara']


In [15]:
print(random.sample(noms, 3))

['Youssef', 'Jean', 'Sara']


In [16]:
print(random.sample(range(20),random.randrange(5)))

[15, 11]


In [17]:
liste=[12,13,4,8,3,69]
random.shuffle(liste)  
"""melanger aléatoirement"""
print(liste)

[4, 12, 8, 69, 13, 3]


In [18]:
liste1=[2,4,6,8,23]
liste2=[True,False,True]
all(liste2)

False

In [19]:
any(liste2)

True

In [20]:
any(liste1)

True

In [21]:
import numpy as np
B=np.array([[1,2,3],[1,2,3],[1,2,3]])
print(np.shape(B)) 
print(B)

(3, 3)
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [22]:
print(np.size(B))

9


In [23]:
print(B.T)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [24]:
print(B.ndim)

2


In [25]:
A=np.zeros((3,4))
print(A)
''' Pour initialiser un tableau à valeur nulle'''

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


' Pour initialiser un tableau à valeur nulle'

In [26]:
A=np.empty((3,4))
print(A)
''' pour reserver la mémoire du tableau  / les valeurs peuvent etre differentes de 0'''

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


' pour reserver la mémoire du tableau  / les valeurs peuvent etre differentes de 0'

In [27]:
C=np.zeros_like(A)
print(C)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
F=np.ones((3,5))
print(F)
''' initialiser un tableau avec des valeurs égale à 1'''

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


' initialiser un tableau avec des valeurs égale à 1'