In [1]:
import numpy as np
A=np.eye(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [2]:
B=np.full((4,4),9)
print(B)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [3]:
C=np.random.randn(10)
print(C)

[ 1.26204654  0.96376504  0.90473486 -0.3566593   1.35059978 -0.74603435
  0.22388519  0.22414509  0.15419784  1.69175555]


In [4]:
D=np.random.randn(3,4)
print(D)

[[-0.68378763 -0.20532058  0.1290805   0.26844903]
 [ 1.17800854  0.41568811 -0.37644765 -0.61622893]
 [ 0.2324838  -0.10253226  1.15887526 -0.29742482]]


In [5]:
E=np.random.randint(1,5,6)
print(E)

[2 2 4 3 1 3]


In [6]:
import numpy as np
F=np.random.random_sample(6)
print(F)

[0.02085681 0.54690892 0.95260483 0.78310953 0.37009785 0.33847436]


In [7]:
G=np.linspace(0,45,5)
print(G)

[ 0.   11.25 22.5  33.75 45.  ]


In [8]:
H=np.arange(7,19,5)
print(H)

[ 7 12 17]


In [9]:
I=np.zeros((4,3,2))
print(I)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [10]:
test1=np.array([6,7,8], dtype='int64')
print(test1)

[6 7 8]


In [11]:
test=np.array([4,9,9], dtype=np.int64)
print(test)

[4 9 9]


In [12]:
U=np.append(test,2)
print(U)

[4 9 9 2]


In [13]:
W=np.hstack((B,A))
print(W)

[[9. 9. 9. 9. 1. 0. 0. 0.]
 [9. 9. 9. 9. 0. 1. 0. 0.]
 [9. 9. 9. 9. 0. 0. 1. 0.]
 [9. 9. 9. 9. 0. 0. 0. 1.]]


In [14]:
X=np.vstack((A,B))
print(X)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]]


In [15]:
Q=np.concatenate((A,B),axis=0)
print(Q)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]]


In [16]:
Q=np.concatenate((A,B),axis=1)
print(Q)

[[1. 0. 0. 0. 9. 9. 9. 9.]
 [0. 1. 0. 0. 9. 9. 9. 9.]
 [0. 0. 1. 0. 9. 9. 9. 9.]
 [0. 0. 0. 1. 9. 9. 9. 9.]]


In [17]:
S=np.arange(8)
print(S)

[0 1 2 3 4 5 6 7]


In [18]:
F=np.reshape(S,(2,4))
print(F)

[[0 1 2 3]
 [4 5 6 7]]


In [19]:
F=np.resize(S,(2,5))
print(F)

[[0 1 2 3 4]
 [5 6 7 0 1]]


In [20]:
print(F.ravel())

[0 1 2 3 4 5 6 7 0 1]


In [21]:
D=np.array([[4,4,4],[5,5,5],[6,6,6],[7,7,7],[8,8,8],[9,9,9]])
print(D)

[[4 4 4]
 [5 5 5]
 [6 6 6]
 [7 7 7]
 [8 8 8]
 [9 9 9]]


In [25]:
T=np.roll(D,-2,axis=0)
print(T)

[[6 6 6]
 [7 7 7]
 [8 8 8]
 [9 9 9]
 [4 4 4]
 [5 5 5]]


In [26]:
print(S[2])

2


In [27]:
print(F[0][3])

3


In [28]:
print(F)

[[0 1 2 3 4]
 [5 6 7 0 1]]


In [29]:
print(F[0:2, 1:3])

[[1 2]
 [6 7]]


In [30]:
print(T[:,0:2])

[[6 6]
 [7 7]
 [8 8]
 [9 9]
 [4 4]
 [5 5]]


In [31]:
print(T[0:2, 0:2])

[[6 6]
 [7 7]]


In [32]:
print(T[:,-2:])

[[6 6]
 [7 7]
 [8 8]
 [9 9]
 [4 4]
 [5 5]]


In [33]:
D=np.array([[1,2,3,6],[4,5,6,7],[7,8,9,10],[10,11,12,2]])
print(D)

[[ 1  2  3  6]
 [ 4  5  6  7]
 [ 7  8  9 10]
 [10 11 12  2]]


In [34]:
D[0:2:1,0:2:1]=3
print(D)

[[ 3  3  3  6]
 [ 3  3  6  7]
 [ 7  8  9 10]
 [10 11 12  2]]


In [35]:
import numpy as np
R=np.arange(16).reshape((4,4))
print(R)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [36]:
S=R.sum(axis=0)
print(S)

[24 28 32 36]


In [37]:
F=R.sum(axis=1)
print(F)

[ 6 22 38 54]


In [38]:
G=np.random.randint(1,10,[3,4])
print(G)

[[4 1 9 7]
 [6 9 9 8]
 [8 1 3 6]]


In [39]:
H=G.cumsum(axis=1)
print(H)

[[ 4  5 14 21]
 [ 6 15 24 32]
 [ 8  9 12 18]]


In [40]:
J=G.prod(axis=0)
print(J)

[192   9 243 336]


In [41]:
print(G.sort(axis=0))

None


In [42]:
G[1,2]=4
G


array([[4, 1, 3, 6],
       [6, 1, 4, 7],
       [8, 9, 9, 8]])

In [43]:
print(G.argsort(axis=1))

[[1 2 0 3]
 [1 2 0 3]
 [0 3 1 2]]


In [44]:
G

array([[4, 1, 3, 6],
       [6, 1, 4, 7],
       [8, 9, 9, 8]])

In [45]:
G.sort(axis=0)
G

array([[4, 1, 3, 6],
       [6, 1, 4, 7],
       [8, 9, 9, 8]])

In [46]:
T=np.random.randint(1,10,[3,4])
print(T)

[[6 6 2 3]
 [9 5 4 6]
 [7 6 3 8]]


In [47]:
L=np.corrcoef(T)
print(L)

[[1.         0.59878495 0.44908871]
 [0.59878495 1.         0.64285714]
 [0.44908871 0.64285714 1.        ]]


In [48]:
K=np.unique(T,axis=0)
K

array([[6, 6, 2, 3],
       [7, 6, 3, 8],
       [9, 5, 4, 6]])

In [49]:
T[np.isnan(T)]=0
T

array([[6, 6, 2, 3],
       [9, 5, 4, 6],
       [7, 6, 3, 8]])

In [50]:
np.isnan(T)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [51]:
D=np.array([[4,4,4],[5,np.nan,5],[6,6,6],[7,np.nan,7]])
print(D)

[[ 4.  4.  4.]
 [ 5. nan  5.]
 [ 6.  6.  6.]
 [ 7. nan  7.]]


In [52]:
np.nanmean(D)

5.4

In [53]:
D=np.array([[4,4,4],[5,5,5],[6,6,6],[7,7,7]])
print(D)

[[4 4 4]
 [5 5 5]
 [6 6 6]
 [7 7 7]]


In [54]:
np.mean(D)

5.5

In [55]:
print(D**3)

[[ 64  64  64]
 [125 125 125]
 [216 216 216]
 [343 343 343]]


In [56]:
print(D*(D**(1/4)))

[[ 5.65685425  5.65685425  5.65685425]
 [ 7.47674391  7.47674391  7.47674391]
 [ 9.39050748  9.39050748  9.39050748]
 [11.38603593 11.38603593 11.38603593]]
